apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: infra-tools
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: oci://registry-1.docker.io/bitnamicharts/postgresql
    targetRevision: 18.6.7
    helm:
      valuesObject:
        architecture: standalone

        auth:
          username: mlops
          password: goit-postgres-password
          database: mlops

        primary:
          persistence:
            enabled: true
            size: 10Gi

          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 500m

        service:
          type: ClusterIP
          port: 5432

  destination:
    server: https://kubernetes.default.svc
    namespace: infra-tools

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
